sudo: required
services:
 - docker

before_install:
 - docker build -t himoura8888/docker-react -f Dockerfile.dev .deploy
 
script:
 - docker run -e CI=true himoura8888/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "eu-west-3"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-eu-west-3-308547679736"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
 


 
